sudo: true

language: python

services:
  - docker

python:
  - "3.7"

before_script: 
  - pip install docker-compose
  - docker-compose build --no-cache

script:
  - docker-compose run backend python manage.py test --no-input
  