version: '3.3'

services:
  backend:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes: 
      - type: bind
        source: .
        target: /backend
    ports:
      - "8000:8000"