version: '3.3'

services:
  backend:
    build: .
    entrypoint: ["./wait-for", "db:5432", "--"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes: 
      - type: bind
        source: .
        target: /backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    privileged: true