FROM python:3

ENV PYTHONNINBUFFERED 1

# Create and set working directory for our source code
RUN mkdir /backend -p -v
WORKDIR /backend
COPY . .

# Install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["gunicorn", "has.wsgi", "--bind" ,"0.0.0.0:8000"]