# Generated by Django 2.2.10 on 2020-02-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_auto_20200205_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='path',
            new_name='file_name',
        ),
    ]
