# Generated by Django 3.0.3 on 2020-02-29 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0004_auto_20200227_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.FloatField()),
                ('y_min', models.FloatField()),
                ('x_max', models.FloatField()),
                ('y_max', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cctv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cctv.CCTV')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cctv.Photo')),
            ],
        ),
    ]
