# Generated by Django 3.0.3 on 2020-03-21 08:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0006_photo_vehicle_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
